services:
  - type: static_site
    name: portfolio-vera-guillen
    buildCommand: echo "No build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

